### PR TITLE
Makefile and build procedure updates for recent (RH) Linux

### PR DESCRIPTION
**Pull request by maxieds**
This PR should integrate the ``Makefile`` changes made for the ``math-mulberry`` applications into the ``master`` branch of the PMFE code. Note that this PR in part replaces the initial larger merge request documented in issue #3.

### CODE REVIEW

**Review by ceheitsch — COMMENTED** [review]
Maxie, would you please explain why the "-frounding-math" flag is needed?

**Comment by maxieds** [comment]
@ceheitsch 
I do not remember exactly what led me to add that option. The [gcc docs](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html) explain what that flag is used to add: 
```
-frounding-math
Disable transformations and optimizations that assume default floating-point rounding behavior. 
This is round-to-zero for all floating point to integer conversions, and round-to-nearest for all other 
arithmetic truncations. This option should be specified for programs that change the FP rounding 
mode dynamically, or that may be executed with a non-default rounding mode. This option disables 
constant folding of floating-point expressions at compile time (which may be affected by rounding
 mode) and arithmetic transformations that are unsafe in the presence of sign-dependent rounding 
modes.

The default is -fno-rounding-math.

This option is experimental and does not currently guarantee to disable all GCC optimizations that 
are affected by rounding mode. Future versions of GCC may provide finer control of this setting 
using C99’s FENV_ACCESS pragma. This command-line option will be used to specify the default 
state for FENV_ACCESS.
```

**Comment by ceheitsch** [comment]
@maxieds It seems more risky than needed to use experimental options.  I've also opened a separate issue about the possibility of using cmake (#22).  On superficial inspection, it seems to address many of the compilation annoyances in a more robust fashion.  Would you please look into it more carefully?  Thanks!

**Comment by maxieds** [comment]
The contents of this pull request are updated in the more recent PR #26 (the Makefile has been renamed there to remove confusion with the new intended CMakeLists build procedure).

**Pull request closed without merging**
